#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg ~/.local/share/wallpapers/ & # set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
#xcompmgr &		# xcompmgr for transparency
picom --conf ~/picom.conf & # Compositor for tranparancy and animations, requires picom-jonaburg, and picom.conf
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
setxkbmap -model pc105 -layout us,ru -option caps:super
